// tool/encode_secrets.dart
//
// Companion of lib/crypto/xor_pipe.dart.  Feeds plaintext secrets through
// the same additive stream that XorPipe.unwind reverses at runtime and
// prints the resulting byte arrays formatted for pasting into
// analytics_bundle.dart / endpoint_bundle.dart.
//
// Usage:
//   dart run tool/encode_secrets.dart
//
// WARNING: do NOT run this via PowerShell foreach loops — integer
// promotion at 32 bits produces wrong bytes on Windows.  Always go
// through `dart run`.
//
// After tweaking the seed in lib/crypto/xor_pipe.dart, you MUST update
// [_seedPhrase] here to the exact same value and re-run this script.
// The two files stay in sync manually — that is intentional so the
// encoder is a *tool* and never imported by the shipping app.

import 'dart:convert';
import 'dart:typed_data';

const String _seedPhrase = 'hd-flame-r0ad!';

Uint8List _streamKey() {
  var state = 0x1E85A7C3;
  for (final unit in _seedPhrase.codeUnits) {
    state = ((state ^ unit) * 0x01000193) & 0xFFFFFFFF;
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= (state >> 17) & 0xFFFFFFFF;
    state ^= (state << 5)  & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
  }
  final key = Uint8List(24);
  for (var i = 0; i < key.length; i++) {
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= (state >> 17) & 0xFFFFFFFF;
    state ^= (state << 5)  & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
    key[i] = (state ^ (i * 0x9E)) & 0xFF;
  }
  return key;
}

int _posOffset(int i) => (i * 7 + (i >> 3) * 11 + 41) & 0xFF;

List<int> _encode(String plaintext) {
  final key = _streamKey();
  final bytes = utf8.encode(plaintext);
  final out = List<int>.filled(bytes.length, 0);
  for (var i = 0; i < bytes.length; i++) {
    final k = key[i % key.length];
    out[i] = (bytes[i] + k + _posOffset(i)) & 0xFF;
  }
  return out;
}

String _format(String label, List<int> bytes) {
  final buf = StringBuffer('// $label\nconst v = <int>[\n  ');
  for (var i = 0; i < bytes.length; i++) {
    buf.write('0x${bytes[i].toRadixString(16).padLeft(2, '0')},');
    if ((i + 1) % 12 == 0 && i != bytes.length - 1) {
      buf.write('\n  ');
    } else if (i != bytes.length - 1) {
      buf.write(' ');
    }
  }
  buf.write('\n];\n');
  return buf.toString();
}

void main(List<String> args) {
  // ------------------------------------------------------------------
  // Fill in plaintext values below, then run:
  //   dart run tool/encode_secrets.dart
  //
  // Copy each printed const into the matching file:
  //   host + path       -> lib/core/endpoint_bundle.dart
  //   AppsFlyer key     -> lib/core/analytics_bundle.dart (attribution key)
  //   FCM project #     -> lib/core/analytics_bundle.dart (messaging id)
  //   GCD host + path   -> lib/core/analytics_bundle.dart (gcd fragments)
  //   Chrome/WebKit UA  -> lib/net/web_fetcher.dart
  // ------------------------------------------------------------------

  const endpointHost = 'https://hendash.com';
  const endpointPath = '/config.php';

  const appsFlyerKey        = '';           // Fill once AppsFlyer key arrives.
  const firebaseProjectId   = '';           // Firebase project number (sender ID).

  const gcdHost = 'https://gcdsdk.appsflyer.com';
  const gcdPath = '/install_data/v4.0/';

  const chromeVersion = '132.0.6834.163';
  const webkitVersion = '537.36';

  final sink = StringBuffer();
  sink.writeln('// Auto-generated by tool/encode_secrets.dart on '
      '${DateTime.now().toIso8601String()}');
  sink.writeln('// Seed: "$_seedPhrase" -- DO NOT commit plaintext values here.');
  sink.writeln();
  sink.writeln(_format('endpoint host', _encode(endpointHost)));
  sink.writeln(_format('endpoint path', _encode(endpointPath)));
  sink.writeln(_format('appsflyer dev key',
      appsFlyerKey.isEmpty ? const <int>[] : _encode(appsFlyerKey)));
  sink.writeln(_format('firebase project id',
      firebaseProjectId.isEmpty ? const <int>[] : _encode(firebaseProjectId)));
  sink.writeln(_format('gcd host', _encode(gcdHost)));
  sink.writeln(_format('gcd path', _encode(gcdPath)));
  sink.writeln(_format('chrome version', _encode(chromeVersion)));
  sink.writeln(_format('webkit version', _encode(webkitVersion)));

  // ignore: avoid_print
  print(sink.toString());
}
